Repository SWU-Team/StudyWithUs, pull requests merged in 2025-04, with the labels that each got.

#23 feat: Room 생성 및 조회 기능 구현
  backend/src/main/java/com/swu/room/controller/RoomController.java
  backend/src/main/java/com/swu/room/domain/Bgm.java
  backend/src/main/java/com/swu/room/domain/Room.java
  backend/src/main/java/com/swu/room/domain/RoomMember.java
  backend/src/main/java/com/swu/room/dto/request/RoomRequest.java
  backend/src/main/java/com/swu/room/dto/response/RoomResponse.java
  backend/src/main/java/com/swu/room/exception/RoomNotFoundException.java
  backend/src/main/java/com/swu/room/service/RoomService.java
Labels: BE, FEATURE

#27 feat: 헤더, 사이드바 UI 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Header.js
  frontend/src/components/Header.module.css
  frontend/src/components/Layout.js
  frontend/src/components/Layout.module.css
  frontend/src/components/Sidebar.js
  frontend/src/components/Sidebar.module.css
  frontend/src/pages/login/Login.js
  frontend/src/pages/planer/Planer.js
  frontend/src/pages/rooms/StudyRoomList.js
Labels: FE, FEATURE

#29 feat: RoomMember 참여/퇴장 기능 및 방장 위임 로직 구현
  backend/src/main/java/com/swu/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/swu/room/controller/RoomController.java
  backend/src/main/java/com/swu/room/controller/RoomMemberController.java
  backend/src/main/java/com/swu/room/domain/Room.java
  backend/src/main/java/com/swu/room/domain/RoomMember.java
  backend/src/main/java/com/swu/room/dto/response/RoomMemberResponse.java
  backend/src/main/java/com/swu/room/exception/AlreadyJoinedRoomException.java
  backend/src/main/java/com/swu/room/exception/NotJoinedRoomException.java
  backend/src/main/java/com/swu/room/exception/RoomFullException.java
  backend/src/main/java/com/swu/room/repository/RoomMemberRepository.java
  backend/src/main/java/com/swu/room/repository/RoomRepository.java
  backend/src/main/java/com/swu/room/service/RoomMemberService.java
  backend/src/main/java/com/swu/room/service/RoomService.java
Labels: BE, FEATURE

#30 chore: Swagger 관련 경로 JWT 필터에서 예외 처리 추가
  backend/src/main/java/com/swu/auth/jwt/JWTFilter.java
Labels: BE, FEATURE

#32 feat: 회원가입 UI 구현
  frontend/src/pages/sighup/Signup.js
  frontend/src/pages/sighup/Signup.module.css
Labels: FE

#34 feat: 로그인 회원가입 API 연결
  frontend/src/pages/login/Login.js
  frontend/src/pages/sighup/Signup.js
Labels: FE, FEATURE

#36 feat: 아이디 찾기, 비밀번호 찾기 UI 구현
  frontend/src/pages/searchid/SearchID.js
  frontend/src/pages/searchid/SearchID.module.css
  frontend/src/pages/searchpw/SearchPW.js
  frontend/src/pages/searchpw/SearchPW.module.css
Labels: FE, FEATURE

#39 feat: WebRTC 시그널링 서버 구현
  backend/src/main/java/com/swu/global/config/WebSocketConfig.java
  backend/src/main/java/com/swu/room/controller/SignalingController.java
  backend/src/main/java/com/swu/room/dto/message/SignalingMessage.java
Labels: BE, FEATURE

#40 feat: STOMP 기반 시그널링에 JWT 인증 로직 및 예외 처리 적용
  backend/src/main/java/com/swu/global/config/StompJwtInterceptor.java
  backend/src/main/java/com/swu/global/config/WebMvcConfig.java
  backend/src/main/java/com/swu/global/config/WebSocketConfig.java
  backend/src/main/java/com/swu/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/swu/room/controller/SignalingController.java
  backend/src/main/java/com/swu/room/dto/message/SignalingMessage.java
  backend/src/main/java/com/swu/room/service/RoomService.java
Labels: BE, FEATURE

#41 feat: 스터디룸 리스트 UI구현
  frontend/src/components/Layout.js
  frontend/src/pages/diary/Diary.js
  frontend/src/pages/mypage/Mypage.js
  frontend/src/pages/rooms/StudyRoomList.js
  frontend/src/pages/rooms/StudyRoomList.module.css
Labels: FE, FEATURE

#46 refactor: 채팅 메시지를 Redis에 저장하고 Pub/Sub 방식으로 전송하도록 구조 개선
  backend/build.gradle
  backend/src/main/java/com/swu/global/config/RedisConfig.java
  backend/src/main/java/com/swu/room/controller/ChatController.java
  backend/src/main/java/com/swu/room/listener/RedisMessageSubscriber.java
  backend/src/main/java/com/swu/room/service/ChatService.java
Labels: BE, REFACTOR

#48 feat: 로그인시 토큰 저장
  frontend/src/pages/login/Login.js
Labels: FE, FEATURE

#53 test: User 관련 단위/통합 테스트 작성
  backend/src/test/java/com/swu/testconfig/TestSecurityConfig.java
  backend/src/test/java/com/swu/testconfig/WithMockCustomUser.java
  backend/src/test/java/com/swu/testconfig/WithMockCustomUserSecurityContextFactory.java
  backend/src/test/java/com/swu/user/controller/UserControllerTest.java
  backend/src/test/java/com/swu/user/service/UserServiceTest.java
Labels: BE

#54 feat: AWS S3 연동 및 이미지 업로드 기능 구현
  backend/build.gradle
  backend/src/main/java/com/swu/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/swu/user/config/S3Config.java
  backend/src/main/java/com/swu/user/controller/UserController.java
  backend/src/main/java/com/swu/user/dto/request/SignupRequest.java
  backend/src/main/java/com/swu/user/exception/ImageUploadFailedException.java
  backend/src/main/java/com/swu/user/exception/InvalidFileException.java
  backend/src/main/java/com/swu/user/util/S3Uploader.java
  backend/src/test/java/com/swu/user/controller/UserControllerTest.java
Labels: BE, FEATURE

#56 feat/마이페이지 UI구성
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/mypage/Mypage.js
  frontend/src/pages/mypage/Mypage.module.css
Labels: FE, FEATURE

#57 feat: 일기 생성 및 조회 기능 구현 및 날짜 직렬화 설정 추가
  backend/build.gradle
  backend/src/main/java/com/swu/diary/controller/DiaryController.java
  backend/src/main/java/com/swu/diary/domain/Diary.java
  backend/src/main/java/com/swu/diary/dto/request/DiaryRequest.java
  backend/src/main/java/com/swu/diary/dto/response/DiaryResponse.java
  backend/src/main/java/com/swu/diary/dto/response/DiarySummaryResponse.java
  backend/src/main/java/com/swu/diary/exception/DiaryAlreadyExistsException.java
  backend/src/main/java/com/swu/diary/exception/DiaryNotFoundException.java
  backend/src/main/java/com/swu/diary/repository/DiaryRepository.java
  backend/src/main/java/com/swu/diary/service/DiaryService.java
  backend/src/main/java/com/swu/global/config/JacksonConfig.java
  backend/src/main/java/com/swu/global/config/RedisConfig.java
  backend/src/main/java/com/swu/global/exception/GlobalExceptionHandler.java
Labels: BE, FEATURE

#59 refactor: 모든 API /api prefix 통일 작업
  backend/src/main/java/com/swu/auth/jwt/JWTFilter.java
  backend/src/main/java/com/swu/auth/jwt/LoginFilter.java
  backend/src/main/java/com/swu/global/config/SecurityConfig.java
  backend/src/main/java/com/swu/global/config/WebSocketConfig.java
  backend/src/main/java/com/swu/room/controller/RoomController.java
  backend/src/main/java/com/swu/room/controller/RoomMemberController.java
  backend/src/main/java/com/swu/user/controller/UserController.java
  frontend/src/pages/login/Login.js
  frontend/src/pages/sighup/Signup.js
Labels: REFACTOR, ALL

#60 chore: GitHub Actions를 통한 GHCR 이미지 빌드 및 PR 테스트 워크플로 추가
  .github/workflows/build-ghcr.yml
  .github/workflows/test-on-pr.yml
  .gitignore
  backend/.env.example
  backend/.gitignore
  backend/Dockerfile
  backend/src/main/resources/application-prod.yml
  backend/src/test/java/com/swu/backend/BackendApplicationTests.java
  backend/src/test/java/com/swu/user/controller/UserControllerTest.java
  docker-compose.prod.yml
  frontend/Dockerfile
  frontend/nginx/nginx.conf
Labels: ALL, CHORE

#61 fix: GHCR 태그명 오류 수정
  .github/workflows/build-ghcr.yml
Labels: INFRA

#62 feat: 환경별 API 주소 분리를 위한 .env 설정 추가
  frontend/src/pages/login/Login.js
  frontend/src/pages/sighup/Signup.js
Labels: FE, REFACTOR, INFRA

#63 feat: 라우팅 구조 및 레이아웃 리팩토링, 인증 흐름 정비
  frontend/src/App.js
  frontend/src/components/Header.module.css
  frontend/src/components/Layout.js
  frontend/src/components/Layout.module.css
  frontend/src/components/Sidebar.js
  frontend/src/components/Sidebar.module.css
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/pages/login/Login.js
  frontend/src/pages/search/SearchID.js
  frontend/src/pages/search/SearchID.module.css
  frontend/src/pages/search/SearchPW.js
  frontend/src/pages/search/SearchPW.module.css
  frontend/src/pages/signup/Signup.js
  frontend/src/pages/signup/Signup.module.css
  frontend/src/pages/startpage/Startpage.js
  frontend/src/utils/auth.js
Labels: FE, REFACTOR, FEATURE

#64 feat: AI 구조 도입
  ai/.gitignore
  ai/README.md
  ai/api/llm_engine.py
  ai/api/main.py
  ai/api/routes.py
  ai/api/schemas.py
  ai/configs/lora_config.py
  ai/configs/training_config.py
  ai/data/merge_datasets.py
  ai/data/study_logs.json
  ai/infer/predict.py
  ai/infer/prompt_template.py
  ai/ollama/Modelfile
  ai/ollama/convert_to_gguf.py
  ai/requirements.txt
Labels: FEATURE, AI

#68 refactor: 레이아웃 구조 개선 및 헤더/사이드바 책임 분리
  frontend/src/App.js
  frontend/src/assets/images/logout.png
  frontend/src/components/Header.js
  frontend/src/components/Header.module.css
  frontend/src/components/Layout.js
  frontend/src/components/Layout.module.css
  frontend/src/components/Sidebar.js
  frontend/src/components/Sidebar.module.css
  frontend/src/index.css
Labels: FE, REFACTOR

#70 feat: axios 요청 템플릿 api.js 적용
  backend/src/main/java/com/swu/global/response/ApiResponse.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/Layout.module.css
  frontend/src/index.js
  frontend/src/pages/login/Login.js
  frontend/src/utils/api.js
  frontend/src/utils/auth.js
Labels: REFACTOR, FEATURE, ALL

#71 feat: JWT 클레임 닉네임 변경 및 인증 실패 처리 적용
  backend/src/main/java/com/swu/auth/handler/CustomAuthenticationEntryPoint.java
  backend/src/main/java/com/swu/auth/jwt/JWTFilter.java
  backend/src/main/java/com/swu/auth/jwt/JWTUtil.java
  backend/src/main/java/com/swu/auth/jwt/LoginFilter.java
  backend/src/main/java/com/swu/config/SecurityConfig.java
  backend/src/main/java/com/swu/domain/user/service/UserService.java
Labels: BE, FEATURE

#72 feat: 레이아웃 리팩터링 및 JWT 기반 닉네임 표시 개선
  frontend/package-lock.json
  frontend/src/components/Header.js
  frontend/src/components/Header.module.css
  frontend/src/components/Layout.module.css
  frontend/src/components/Sidebar.js
  frontend/src/components/Sidebar.module.css
  frontend/src/utils/api.js
  frontend/src/utils/auth.js
Labels: FE, REFACTOR, FEATURE

#74 feat: 모바일 헤더 햄버거 사이드바 추가
  frontend/src/components/Header.js
  frontend/src/components/Header.module.css
  frontend/src/components/MobileSidebar.js
  frontend/src/components/MobileSidebar.module.css
  frontend/src/components/Sidebar.module.css
Labels: FE, FEATURE
